version: '3'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
